language: php

php:
  - 7.1
  - 7.2
  - 7.3

before_script:
  - composer install --no-interaction

script:
  - echo $(phpenv version-name)
  - curl -sSfL -o ~/.phpenv/versions/$(phpenv version-name)/bin/phpunit https://phar.phpunit.de/phpunit-6.5.9.phar
  - phpunit --version
  - phpunit --configuration phpunit.xml

after_script:
  - travis_retry php vendor/bin/php-coveralls -v
